Going back to Jersey 3.0.8 because of JDK 8 incompatibility:
Error:  /home/runner/work/radiobrowser4j/radiobrowser4j/radiobrowser4j/src/main/java/de/sfuhrm/radiobrowser4j/ListParameter.java:[23,26] cannot access jakarta.ws.rs.core.MultivaluedMap
  bad class file: /home/runner/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs-api-3.1.0.jar(jakarta/ws/rs/core/MultivaluedMap.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.